name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer (Forcing Automate)
        run: |
          mkdir -p bin
          # O comando 'yes |' envia 'y' infinitamente para qualquer pergunta
          docker run --rm \
            -v ${{ github.workspace }}:/home/user/hostdir \
            kivy/buildozer:latest \
            /bin/bash -c "yes | buildozer android debug"
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MeuAppAPK
          path: bin/*.apk
