name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer (O Caminho Definitivo)
        run: |
          mkdir -p bin
          # Usamos o Docker oficial, mas injetamos o comando que pula a trava de seguran√ßa
          docker run --rm \
            -v ${{ github.workspace }}:/home/user/hostdir \
            kivy/buildozer:latest \
            /bin/bash -c "export FORCE_BUILDOZER_ALLOW_ROOT=1 && buildozer android debug"
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MeuAppAPK
          path: bin/*.apk
