name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer Docker (Fix Root & Automate)
        run: |
          # Criamos a pasta bin para evitar erros de permiss√£o no upload
          mkdir -p bin
          docker run --rm \
            --user root \
            -e "BUILD_USER=$(id -u -n)" \
            -v ${{ github.workspace }}:/home/user/hostdir \
            kivy/buildozer:latest \
            android debug --yes
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MeuAppAPK
          path: bin/*.apk
