name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Buildozer e Dependências
        run: |
          pip install --upgrade pip
          pip install buildozer cython==0.29.33

      - name: Instalar Android Build-Tools e AIDL
        run: |
          # O AIDL fica dentro das build-tools. Vamos garantir que elas existam.
          sudo apt-get install -y adb
          # Localizando e adicionando o AIDL ao PATH
          export ANDROID_SDK_ROOT=$ANDROID_HOME
          export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/build-tools/34.0.0
          echo "$ANDROID_SDK_ROOT/build-tools/34.0.0" >> $GITHUB_PATH

      - name: Build with Buildozer
        run: |
          # Forçamos o uso do caminho correto durante o build
          export APP_ALLOW_KIVY_INSTALL_AS_ROOT=1
          buildozer android debug --yes

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MeuAppInstalavel
          path: bin/*.apk
